### ISSUE TITLE
EaxCast is dead

### ISSUE THREAD

**Issue by Fi5t** [AveVlad/russia-it-podcast#48]
О чем неоднократно говорил @afiskon. Думаю стоит добавить эту инфу в описание.

**Comment by AveVlad** [comment]
https://github.com/AveVlad/russia-it-podcast/pull/21#issuecomment-132744633

**Comment by afiskon** [comment]
На мой взгляд старые выпуски все еще имеют некоторую ценность и будут ее иметь еще пару лет как минимум. EaxCast мы старались делать на века. Я, впрочем, ни на чем не настаиваю, да и мопед уже не мой. сс: @sumerman

**Comment by afiskon** [comment]
А, вы просто инфу хотите поправить? Я чето-то решил что выпилить! Ну да, вреда не будет :)

**Comment by Fi5t** [comment]
@afiskon про ценность выпусков я согласен. Просто стоит указать, что выход подкаста временно приостановлен. В описании просто значится, что
`Подкаст публикуется эпизодами по 40-45 минут каждые две недели.`
Это может ввести в заблуждение людей, которые еще его не слушали, а так же не слушают devzen где мелькала инфа про холд eaxcast-а.

**Comment by sumerman** [comment]
@Fi5t некоторое время я лелеял идею возродить EaxCast, но:
- У меня не чтобы много времени — к тому же DevZen нужно готовиться + в Берлине у меня внезапно появилась жизнь :)
- DevZen с сильно сдвинулся с точки "я бы не стал слушать это сам потому что 2 часа болтовни" в сторону "я слушаю и переслушиваю даже если я был в выпуске несмотря на 2 часа"

Bottomline IMO:
- ссылку на EaxCast оставлять нужно
- в ближайшее время он выходить не будет

**Comment by Fi5t** [comment]
@sumerman жалко EaxCast. Было интересно! Если когда-нибудь получиться его возродить в том же формате, то я бы охотно послушал.

**Comment by sumerman** [comment]
@Fi5t так он потому и умер — мы подняли планку так высоко, что держать это на регулярной основе просто невозможно.

**Comment by afiskon** [comment]
@Fi5t все в ваших руках - берите интервью из DevZen, делайте их текстовую расшифровку, публикуйте. Можем на devzen.ru публиковать или на eax.me если хотите. Но самим заниматься этим совершенно нереально.

**Comment by AveVlad** [comment]
такие дела
