### ISSUE TITLE
golangshow.com

### ISSUE THREAD

**Issue by AlekSi** [AveVlad/russia-it-podcast#7]

**Comment by AveVlad** [comment]
@AlekSi давай PR

**Comment by outcoldman** [comment]
@AlekSi вы же один из ведущих подкаста, знаете, наверное, как Open Source работает. Откройте Pull Request с ссылками на twitter и GitHub если можно. 

Без обид, но такой открытый issue выглядит уж очень не красиво с вашей стороны. Кто как не вы можете собрать необходимую информацию и добавить подкаст в список?

**Comment by AlekSi** [comment]
У нас проблемы были с добавлением в iTunes, в конце недели только решили. Сейчас сделаю.
